"""foreign phrase table

Revision ID: 61d1e5649f0f
Revises: 
Create Date: 2019-04-05 15:03:59.003356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d1e5649f0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foreign_phrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_message', sa.String(length=2000), nullable=True),
    sa.Column('original_language', sa.String(length=30), nullable=True),
    sa.Column('english_translation', sa.String(length=3000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_phrase_timestamp'), 'foreign_phrase', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foreign_phrase_timestamp'), table_name='foreign_phrase')
    op.drop_table('foreign_phrase')
    # ### end Alembic commands ###
